# Generated by Django 5.1.2 on 2024-11-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='content',
            field=models.TextField(default='This is a test content'),
            preserve_default=False,
        ),
    ]
